docker images: List all images available on the local system.

#+BEGIN_SRC bash
docker images
#+END_SRC 

docker pull: Pull an image or a repository from a registry.

#+BEGIN_SRC bash
docker pull <image_name>:<tag>
#+END_SRC 

docker build: Build an image from a Dockerfile.

#+BEGIN_SRC bash
docker build -t <image_name>:<tag> <path_to_Dockerfile>
#+END_SRC

docker rmi: Remove one or more images from the local system.

#+BEGIN_SRC bash
docker rmi <image_id>
#+END_SRC

docker tag: Tag an image into a repository.

#+BEGIN_SRC bash
docker tag <source_image>:<tag> <target_repository>:<tag>
#+END_SRC

docker history: Show the history of an image.

#+BEGIN_SRC bash
docker history <image_name>:<tag>
#+END_SRC

docker inspect: Display detailed information on one or more images.

#+BEGIN_SRC bash
docker inspect <image_name>
#+END_SRC

docker save: Save one or more images to a tar archive.

#+BEGIN_SRC bash
docker save -o <output_file.tar> <image_name>:<tag>
#+END_SRC

docker load: Load an image from a tar archive.

#+BEGIN_SRC bash
docker load -i <input_file.tar>
#+END_SRC

docker prune: (Add '-a' to remove dangling resources)

Remove all unused images.

#+BEGIN_SRC bash
docker image prune
#+END_SRC

Remove a wider range of unused Docker resources, including images, containers, networks, and volumes. 

#+BEGIN_SRC bash
docker system prune
#+END_SRC

docker search: Search for an image on a Docker registry.

#+BEGIN_SRC bash
docker search <search_term>
#+END_SRC

docker push: Push an image or a repository to a registry.

#+BEGIN_SRC bash
docker push <image_name>:<tag>
#+END_SRC
